update github release workflow

diff --git a/.github/workflows/windows-arm-build.yml b/.github/workflows/windows-arm-build.yml
--- a/.github/workflows/windows-arm-build.yml
+++ b/.github/workflows/windows-arm-build.yml
@@ -4,12 +4,18 @@ on:
   push:
     tags:
 
+permissions:
+  id-token: write # needed for attestion
+  attestations: write
+  contents: write  # needed for release update
+
 jobs:
-  build:
+  build-and-release-arm:
     runs-on: windows-11-arm
     env:
       ARCH: x64
       DEPENDENCIES: c:\dependencies
+      GH_TAG_NAME: ${{ github.ref_name }}
 
     steps:
       - name: Checkout repository
@@ -52,6 +58,7 @@ jobs:
           call vcvarsall.bat x64_arm64
           call appveyor.bat build
 
+      # Skip the test for now, it still fails
 #      - name: Test Vim
 #        shell: cmd
 #        run: |
@@ -64,24 +71,72 @@ jobs:
           call appveyor.bat package
 
       - name: upload Installer
+        id:   upload-installer
         uses: actions/upload-artifact@v4
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
-          upload_url: ${{ github.event.release.upload_url }}
-          name: arm64-windows-installer
+          name: arm64-windows-installer.exe
           path: |
             gvim*.exe
 
+      - name: Attest Installer
+        uses: actions/attest-build-provenance@v2
+        with:
+          subject-name: arm64-windows-installer.exe
+          subject-digest: sha256:${{ steps.upload-installer.outputs.artifact-digest }}
+
       - name: upload Zip File
+        id:   upload-zip
         uses: actions/upload-artifact@v4
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
-          upload_url: ${{ github.event.release.upload_url }}
-          name: arm64-windows-zip-archive
+          name: arm64-windows-zip-archive.zip
           path: |
             gvim*.zip
+
+      - name: Attest Zip File
+        uses: actions/attest-build-provenance@v2
+        with:
+          subject-name: arm64-windows-zip-archive.zip
+          subject-digest: sha256:${{ steps.upload-zip.outputs.artifact-digest }}
+
+      # the release will be created by the appveyor CI, so we need to wait
+      # until it exists before trying to push our release artifacts
+      - name: Wait for Github Release
+        shell: bash
+        env:
+          TAG_NAME: ${{ github.ref_name }}
+        run: |
+          echo "Waiting for release with tag $TAG_NAME..."
+          for i in {1..30}; do
+            STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
+              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+              https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG_NAME)
+
+            if [ "$STATUS" -eq 200 ]; then
+              echo "✅ Release $TAG_NAME exists!"
+              exit 0
+            else
+              echo "⏳ Attempt $i: Release not found yet. Waiting 60s..."
+              sleep 60
+            fi
+          done
+
+          echo "❌ Timed out waiting for release $TAG_NAME"
+          exit 1
+
+
+      - name: Upload to Github Release
+        shell: bash
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          for i in gvim*.exe *.zip; do
+            gh release upload "$GH_TAG_NAME" "$i" --clobber
+          done
+
 
 #      - name: Upload Signpath File
 #        uses: actions/upload-artifact@v4
@@ -91,4 +146,4 @@ jobs:
 #          upload_url: ${{ github.event.release.upload_url }}
 #          name: arm64-windows-signpath
 #          path: |
-            unsigned-*.zip
+#            unsigned-*.zip
