debug

diff --git a/.github/workflows/winget_stable.yml b/.github/workflows/winget_stable.yml
--- a/.github/workflows/winget_stable.yml
+++ b/.github/workflows/winget_stable.yml
@@ -10,17 +10,17 @@ jobs:
     steps:
       - name: Check updates
         id: check-updates
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           LAST_RUN=$(gh run list --workflow winget_stable.yml -L 1 -s success >/dev/null 2>&1 |awk '{print $3}')
           LAST_STABLE_RELEASE=$(if echo $LAST_RUN |grep -qs '\.' >/dev/null; then echo "$LAST_RUN" | tr -d '\.v'; else echo "0"; fi)
           LAST_STABLE_RELEASE=$(( ${LAST_STABLE_RELEASE} + 200 ))
           echo "LAST_STABLE_RELEASE $LAST_STABLE_RELEASE"
-          bash -cx "gh run list" || echo "error"
+          bash -cvx "gh run list" >> $GITHUB_OUTPUT || echo "error"
           LAST_RELEASE=$(echo ${GITHUB_REF_NAME} |tr -d '.v')
           echo "LAST_RELEASE $LAST_RELEASE"
           echo "result=$([[ ${LAST_RELEASE} -gt ${LAST_STABLE_RELEASE} ]] && echo true)" >> "$GITHUB_OUTPUT"
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   publish-winget-stable:
     runs-on: windows-latest # action can only be run on windows
